# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kauth': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kwallet': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kdbusaddons': '@stable' 
    'frameworks/knotifications': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kauth': '@stable'
    'frameworks/kservice': '@stable'     
    'frameworks/kwallet': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kcrash': '@stable'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
